<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Games.aspx.cs" Inherits="Petanque.Games" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <br />
    <asp:HyperLink NavigateUrl="~/AddGame" Text="Add new game" runat="server" />

    <br /><br />

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />

    <asp:GridView runat="server" ID="gamesGrid" ItemType="Petanque.Models.Game"  DataKeyNames="GameID" 
        SelectMethod="gamesGrid_GetData" AutoGenerateColumns="False"
        UpdateMethod="gamesGrid_UpdateItem" DeleteMethod="gamesGrid_DeleteItem"
        OnRowDataBound="gamesGrid_RowDataBound" OnRowUpdating="gamesGrid_RowUpdating" CausesValidation="False"
        autoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowPaging="true" PageSize="25">
        <Columns>
            
            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Winner 1" SortExpression="Winner1Id">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="Winner1DD" Mode="edit" DataField="Winner1" 
                        DataSource="<%# GetUserNamesWithoutNoone() %>" SelectedValue="<%# BindItem.Winner1.Name %>" >
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Winner1Label" runat="server" DataField="Winner1Id" Text="<%# GetUserNameById(Item.Winner1Id) %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Winner 2" SortExpression="Winner2Id">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="Winner2DD" Mode="edit" DataField="Winner2" 
                        DataSource="<%# GetUserNames() %>" SelectedValue="<%# BindItem.Winner2.Name %>" >
                    </asp:DropDownList>
                 </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Winner2Label" runat="server" DataField="Winner2Id" Text="<%# GetUserNameById(Item.Winner2Id) %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Winner 3" SortExpression="Winner3Id">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="Winner3DD" Mode="edit" DataField="Winner3" 
                        DataSource="<%# GetUserNames() %>" SelectedValue="<%# BindItem.Winner3.Name %>" >
                    </asp:DropDownList>
                 </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Winner3Label" runat="server" DataField="Winner3Id" Text="<%# GetUserNameById(Item.Winner3Id) %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Loser 1" SortExpression="Loser1Id">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="Loser1DD" Mode="edit" DataField="Loser1" 
                        DataSource="<%# GetUserNamesWithoutNoone() %>" SelectedValue="<%# BindItem.Loser1.Name %>" >
                    </asp:DropDownList>
                 </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Loser1Label" runat="server" DataField="Loser1Id" Text="<%# GetUserNameById(Item.Loser1Id) %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Loser 2" SortExpression="Loser2Id">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="Loser2DD" Mode="edit" DataField="Loser2" 
                        DataSource="<%# GetUserNames() %>" SelectedValue="<%# BindItem.Loser2.Name %>" >
                    </asp:DropDownList>
                 </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Loser2Label" runat="server" DataField="Loser2Id" Text="<%# GetUserNameById(Item.Loser2Id) %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Loser 3" SortExpression="Loser3Id">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="Loser3DD" Mode="edit" DataField="Loser3" 
                        DataSource="<%# GetUserNames() %>" SelectedValue="<%# BindItem.Loser3.Name %>" >
                    </asp:DropDownList>
                 </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Loser3Label" runat="server" DataField="Loser3Id" Text="<%# GetUserNameById(Item.Loser3Id) %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Losing Score" SortExpression="LosingScore">
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="LosingScoreDD" Mode="edit" DataField="LosingScore" 
                        DataSource="<%# GetPossibleLosingScores() %>" SelectedValue="<%# BindItem.LosingScore %>" >
                    </asp:DropDownList>
                 </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LosingScoreLabel" runat="server" DataField="LosingScore" Text="<%# Item.LosingScore %>" Mode="ReadOnly" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:DynamicField DataField="Date" />
            <asp:DynamicField DataField="League" />
        </Columns>
    </asp:GridView>


</asp:Content>
