<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Members.aspx.cs" Inherits="Petanque.Members" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <br />
    <asp:HyperLink NavigateUrl="~/AddMember" Text="Add new member" runat="server" />

    <br /><br />
    <asp:Label runat="server" Text="Show:" />
    <asp:DropDownList runat="server" AutoPostBack="true" ID="AgeBracket">
        <asp:ListItem Text="All" Value="" />
        <asp:ListItem Text="Junior" />
        <asp:ListItem Text="Adult" />
        <asp:ListItem Text="Senior" />
    </asp:DropDownList>

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />

    <asp:GridView runat="server" ID="usersGrid" ItemType="Petanque.Models.User"  DataKeyNames="UserID" 
        SelectMethod="usersGrid_GetData" AutoGenerateColumns="false"
        UpdateMethod="usersGrid_UpdateItem" DeleteMethod="usersGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:DynamicField DataField="UserID" />
            <asp:DynamicField DataField="Name" />
            <asp:DynamicField DataField="AgeRange" />
        </Columns>
    </asp:GridView>

</asp:Content>
